const productsData = [
    // Chocolatería
    { id: 1, name: 'Chocolate Amargo', category: 'Chocolatería', price: 50, image: '/img/chocolate1.jpg' },
    { id: 2, name: 'Trufas Clásicas', category: 'Chocolatería', price: 60, image: '/img/chocolate2.jpg' },
    { id: 3, name: 'Tableta de Cacao 70%', category: 'Chocolatería', price: 45, image: '/img/chocolate3.jpg' },
    { id: 4, name: 'Chocolate con Almendras', category: 'Chocolatería', price: 55, image: '/img/chocolate4.jpg' },
    { id: 5, name: 'Barras Rellenas', category: 'Chocolatería', price: 48, image: '/img/chocolate5.jpg' },
    { id: 6, name: 'Chocolate Blanco', category: 'Chocolatería', price: 52, image: '/img/chocolate6.jpg' },
    { id: 7, name: 'Chocolate con Naranja', category: 'Chocolatería', price: 53, image: '/img/chocolate7.jpg' },
    { id: 8, name: 'Chocolate con Menta', category: 'Chocolatería', price: 50, image: '/img/chocolate8.jpg' },
    { id: 9, name: 'Chocolate Artesanal', category: 'Chocolatería', price: 70, image: '/img/chocolate9.jpg' },
    { id: 10, name: 'Bombones de Chocolate', category: 'Chocolatería', price: 62, image: '/img/chocolate10.jpg' },
    { id: 11, name: 'Mini Trufas', category: 'Chocolatería', price: 40, image: '/img/chocolate11.jpg' },
    { id: 12, name: 'Chocotejas', category: 'Chocolatería', price: 65, image: '/img/chocolate12.jpg' },
    { id: 13, name: 'Chocolate con Fresa', category: 'Chocolatería', price: 58, image: '/img/chocolate13.jpg' },
    { id: 14, name: 'Chocolate con Café', category: 'Chocolatería', price: 60, image: '/img/chocolate14.jpg' },
    { id: 15, name: 'Chocolate con Pistache', category: 'Chocolatería', price: 63, image: '/img/chocolate15.jpg' },

    // Dulces
    { id: 16, name: 'Gomitas de Fruta', category: 'Dulces', price: 20, image: '/img/dulce1.jpg' },
    { id: 17, name: 'Caramelos Surtidos', category: 'Dulces', price: 18, image: '/img/dulce2.jpg' },
    { id: 18, name: 'Paletas de Sabores', category: 'Dulces', price: 15, image: '/img/dulce3.jpg' },
    { id: 19, name: 'Dulces Picantes', category: 'Dulces', price: 22, image: '/img/dulce4.jpg' },
    { id: 20, name: 'Tamarindo', category: 'Dulces', price: 19, image: '/img/dulce5.jpg' },
    { id: 21, name: 'Pulparindo', category: 'Dulces', price: 21, image: '/img/dulce6.jpg' },
    { id: 22, name: 'Mazapán', category: 'Dulces', price: 23, image: '/img/dulce7.jpg' },
    { id: 23, name: 'Rollitos de Fruta', category: 'Dulces', price: 17, image: '/img/dulce8.jpg' },
    { id: 24, name: 'Chicles', category: 'Dulces', price: 10, image: '/img/dulce9.jpg' },
    { id: 25, name: 'Dulces de Leche', category: 'Dulces', price: 25, image: '/img/dulce10.jpg' },
    { id: 26, name: 'Dulces Ácidos', category: 'Dulces', price: 18, image: '/img/dulce11.jpg' },
    { id: 27, name: 'Pastillas de Menta', category: 'Dulces', price: 14, image: '/img/dulce12.jpg' },
    { id: 28, name: 'Caramelos Rellenos', category: 'Dulces', price: 19, image: '/img/dulce13.jpg' },
    { id: 29, name: 'Gomitas Ácidas', category: 'Dulces', price: 20, image: '/img/dulce14.jpg' },
    { id: 30, name: 'Duvalín', category: 'Dulces', price: 12, image: '/img/dulce15.jpg' },

    // Postres
    { id: 31, name: 'Cheesecake', category: 'Postres', price: 85, image: '/img/postre1.jpg' },
    { id: 32, name: 'Pastel de Chocolate', category: 'Postres', price: 90, image: '/img/postre2.jpg' },
    { id: 33, name: 'Brownie', category: 'Postres', price: 60, image: '/img/postre3.jpg' },
    { id: 34, name: 'Flan Napolitano', category: 'Postres', price: 50, image: '/img/postre4.jpg' },
    { id: 35, name: 'Gelatina', category: 'Postres', price: 25, image: '/img/postre5.jpg' },
    { id: 36, name: 'Tiramisú', category: 'Postres', price: 70, image: '/img/postre6.jpg' },
    { id: 37, name: 'Pastel Tres Leches', category: 'Postres', price: 85, image: '/img/postre7.jpg' },
    { id: 38, name: 'Mousse de Chocolate', category: 'Postres', price: 68, image: '/img/postre8.jpg' },
    { id: 39, name: 'Tarta de Frutas', category: 'Postres', price: 72, image: '/img/postre9.jpg' },
    { id: 40, name: 'Cupcakes', category: 'Postres', price: 30, image: '/img/postre10.jpg' },
    { id: 41, name: 'Churros Rellenos', category: 'Postres', price: 40, image: '/img/postre11.jpg' },
    { id: 42, name: 'Galletas Decoradas', category: 'Postres', price: 35, image: '/img/postre12.jpg' },
    { id: 43, name: 'Helado Artesanal', category: 'Postres', price: 55, image: '/img/postre13.jpg' },
    { id: 44, name: 'Pastel de Zanahoria', category: 'Postres', price: 80, image: '/img/postre14.jpg' },
    { id: 45, name: 'Pay de Limón', category: 'Postres', price: 65, image: '/img/postre15.jpg' },

    // Panadería
    { id: 46, name: 'Concha', category: 'Panaderia', price: 12, image: '/img/pan1.jpg' },
    { id: 47, name: 'Cuernito', category: 'Panaderia', price: 15, image: '/img/pan2.jpg' },
    { id: 48, name: 'Pan de Muerto', category: 'Panaderia', price: 20, image: '/img/pan3.jpg' },
    { id: 49, name: 'Oreja', category: 'Panaderia', price: 14, image: '/img/pan4.jpg' },
    { id: 50, name: 'Bollito', category: 'Panaderia', price: 13, image: '/img/pan5.jpg' },
    { id: 51, name: 'Cocol', category: 'Panaderia', price: 16, image: '/img/pan6.jpg' },
    { id: 52, name: 'Bigote', category: 'Panaderia', price: 14, image: '/img/pan7.jpg' },
    { id: 53, name: 'Pan Danés', category: 'Panaderia', price: 18, image: '/img/pan8.jpg' },
    { id: 54, name: 'Trenza de Chocolate', category: 'Panaderia', price: 22, image: '/img/pan9.jpg' },
    { id: 55, name: 'Pan de Elote', category: 'Panaderia', price: 19, image: '/img/pan10.jpg' },
    { id: 56, name: 'Pan Integral', category: 'Panaderia', price: 17, image: '/img/pan11.jpg' },
    { id: 57, name: 'Empanada de Piña', category: 'Panaderia', price: 15, image: '/img/pan12.jpg' },
    { id: 58, name: 'Mantecadas', category: 'Panaderia', price: 16, image: '/img/pan13.jpg' },
    { id: 59, name: 'Pan de Queso', category: 'Panaderia', price: 20, image: '/img/pan14.jpg' },
    { id: 60, name: 'Panecillo Relleno', category: 'Panaderia', price: 21, image: '/img/pan15.jpg' },

    // Malvaviscos
    { id: 61, name: 'Malvaviscos Blancos', category: 'Malvaviscos', price: 18, image: '/img/malva1.jpg' },
    { id: 62, name: 'Malvaviscos Sabor Fresa', category: 'Malvaviscos', price: 20, image: '/img/malva2.jpg' },
    { id: 63, name: 'Malvaviscos Surtidos', category: 'Malvaviscos', price: 22, image: '/img/malva3.jpg' },
    { id: 64, name: 'Malvaviscos Cubiertos de Chocolate', category: 'Malvaviscos', price: 30, image: '/img/malva4.jpg' },
    { id: 65, name: 'Mini Malvaviscos', category: 'Malvaviscos', price: 15, image: '/img/malva5.jpg' },
    { id: 66, name: 'Malvaviscos en Forma de Corazón', category: 'Malvaviscos', price: 25, image: '/img/malva6.jpg' },
    { id: 67, name: 'Malvaviscos Tostados', category: 'Malvaviscos', price: 26, image: '/img/malva7.jpg' },
    { id: 68, name: 'Malvaviscos con Relleno', category: 'Malvaviscos', price: 28, image: '/img/malva8.jpg' },
    { id: 69, name: 'Malvaviscos de Colores', category: 'Malvaviscos', price: 19, image: '/img/malva9.jpg' },
    { id: 70, name: 'Malvaviscos en Forma de Estrella', category: 'Malvaviscos', price: 24, image: '/img/malva10.jpg' },
    { id: 71, name: 'Malvaviscos XL', category: 'Malvaviscos', price: 27, image: '/img/malva11.jpg' },
    { id: 72, name: 'Malvaviscos Decorativos', category: 'Malvaviscos', price: 22, image: '/img/malva12.jpg' },
    { id: 73, name: 'Malvaviscos Gigantes', category: 'Malvaviscos', price: 29, image: '/img/malva13.jpg' },
    { id: 74, name: 'Malvaviscos Cítricos', category: 'Malvaviscos', price: 21, image: '/img/malva14.jpg' },
    { id: 75, name: 'Malvaviscos Espolvoreados', category: 'Malvaviscos', price: 23, image: '/img/malva15.jpg' },
];

export default productsData